### ISSUE TITLE
Override `table` styling in docs

### ISSUE THREAD

**Issue by pumbas600** [JamesNZL/algovision#26]
The tables in the docs have the `border-collapse: separate;` style applied to `table` elements, which causes the double border effect seen below.

![image](https://github.com/JamesNZL/algovision/assets/38820160/0fce4905-d50d-4eee-8fa3-821e374f44b9)

Using `border-collapse: collapse;` will prevent this effect :)

**Comment by JamesNZL** [comment]
thanks ❤️

**Comment by JamesNZL** [comment]
![image](https://github.com/JamesNZL/algovision/assets/44986932/6600592c-e1ac-4046-a0ff-9f3bd8a4646e)

https://docs.jamesnzl.xyz/algovision

:)))
